"""Render a ThreatModel as Markdown and as OWASP Threat Dragon v2 JSON.

The Markdown is the human-facing artefact: component-grouped, then
STRIDE-grouped within each component, with severity sorted high to
low. The JSON is the machine artefact and follows the OWASP Threat
Dragon v2 schema sufficiently for the file to import into Threat
Dragon as a starting model — components become process / store /
actor cells, and threats attach to the corresponding cell."""
from __future__ import annotations

import hashlib
import json
import uuid
from pathlib import Path
from typing import Any

from .parser import ComponentType, SystemDescription
from .validator import Severity, StrideCategory, Threat, ThreatModel


_SEV_ORDER = {
    Severity.CRITICAL.value: 0,
    Severity.HIGH.value:     1,
    Severity.MEDIUM.value:   2,
    Severity.LOW.value:      3,
    Severity.INFO.value:     4,
}

_STRIDE_LETTER = {
    StrideCategory.SPOOFING:               "S",
    StrideCategory.TAMPERING:              "T",
    StrideCategory.REPUDIATION:            "R",
    StrideCategory.INFORMATION_DISCLOSURE: "I",
    StrideCategory.DENIAL_OF_SERVICE:      "D",
    StrideCategory.ELEVATION_OF_PRIVILEGE: "E",
}

_STRIDE_LABEL = {
    StrideCategory.SPOOFING:               "Spoofing",
    StrideCategory.TAMPERING:              "Tampering",
    StrideCategory.REPUDIATION:            "Repudiation",
    StrideCategory.INFORMATION_DISCLOSURE: "Information Disclosure",
    StrideCategory.DENIAL_OF_SERVICE:      "Denial of Service",
    StrideCategory.ELEVATION_OF_PRIVILEGE: "Elevation of Privilege",
}


def _sev_value(t: Threat) -> str:
    return t.severity.value if hasattr(t.severity, "value") else t.severity


def _cat_value(t: Threat) -> StrideCategory:
    return t.stride_category if isinstance(t.stride_category, StrideCategory) \
        else StrideCategory(t.stride_category)


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------

def render_markdown(model: ThreatModel) -> str:
    lines: list[str] = []
    lines.append(f"# Threat Model: {model.system_name}")
    lines.append("")
    lines.append(f"- **Generated:** {model.generated_at}")
    lines.append(f"- **Total threats:** {model.threat_count}")
    if model.augmentation:
        prov = model.augmentation.get("provider", "rules-only")
        status = model.augmentation.get("status", "n/a")
        lines.append(f"- **LLM augmentation:** "
                     f"`{prov}` · status `{status}`")
    lines.append("")

    # Severity rollup.
    by_sev: dict[str, int] = {}
    for t in model.threats:
        by_sev[_sev_value(t)] = by_sev.get(_sev_value(t), 0) + 1
    lines.append("## Severity rollup")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---:|")
    for s in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
               Severity.LOW, Severity.INFO):
        lines.append(f"| {s.value} | {by_sev.get(s.value, 0)} |")
    lines.append("")

    # Per-component, then STRIDE-sorted, then severity-sorted.
    grouped = model.by_component()
    for component, threats in grouped.items():
        if not threats:
            continue
        lines.append(f"## Component: `{component}`")
        ctype = threats[0].component_type
        lines.append(f"_Component type: `{ctype}`._")
        lines.append("")

        by_cat: dict[str, list[Threat]] = {}
        for t in threats:
            cat = _cat_value(t).value
            by_cat.setdefault(cat, []).append(t)

        for cat in [c.value for c in StrideCategory]:
            if cat not in by_cat:
                continue
            lines.append(f"### {_STRIDE_LABEL[StrideCategory(cat)]} "
                         f"({_STRIDE_LETTER[StrideCategory(cat)]})")
            lines.append("")
            ts = sorted(by_cat[cat],
                         key=lambda t: _SEV_ORDER.get(_sev_value(t), 9))
            for t in ts:
                lines.append(
                    f"- **{t.title}** _(severity: {_sev_value(t)}; "
                    f"source: `{t.source}`)_")
                lines.append(f"  - {t.description}")
                lines.append(f"  - **Recommendation:** {t.recommendation}")
                if t.references:
                    lines.append("  - References: "
                                 + "; ".join(t.references))
                lines.append(f"  - _Threat id: `{t.threat_id}`._")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Generated by [`threat-model-generator`]"
                 "(https://github.com/thunderstornX/threat-model-generator). "
                 "This is a first-pass draft, not a finished model._")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# OWASP Threat Dragon v2 JSON
# ---------------------------------------------------------------------------

# Threat Dragon v2 cell types, by our component_type.
_TD_CELL_TYPE = {
    ComponentType.WEB_FRONTEND.value:     "tm.Process",
    ComponentType.API.value:              "tm.Process",
    ComponentType.DATABASE.value:         "tm.Store",
    ComponentType.QUEUE.value:            "tm.Store",
    ComponentType.STORAGE.value:          "tm.Store",
    ComponentType.AUTH_SERVICE.value:     "tm.Process",
    ComponentType.MOBILE_CLIENT.value:    "tm.Actor",
    ComponentType.IOT_DEVICE.value:       "tm.Actor",
    ComponentType.EXTERNAL_SERVICE.value: "tm.Actor",
}


def _stable_uuid(s: str) -> str:
    """Deterministic UUIDv4-shaped id from a string seed.

    Threat Dragon expects UUIDs; using a hash-derived stable value
    keeps rerendered models diff-friendly. SHA-256 is used purely for
    its deterministic-digest property; this is not a cryptographic
    integrity primitive in our codebase."""
    h = hashlib.sha256(s.encode("utf-8")).digest()
    return str(uuid.UUID(bytes=h[:16], version=4))


def render_threat_dragon(
    system: SystemDescription, model: ThreatModel,
) -> dict[str, Any]:
    """Render a Threat Dragon v2-shaped JSON dict for the model."""
    grouped = model.by_component()

    cells: list[dict[str, Any]] = []
    # Lay out cells in a simple horizontal row, 220px apart.
    x_step = 220
    y = 200
    x = 80
    for c in system.components:
        cell_id = _stable_uuid(f"{system.name}::component::{c.name}")
        cell_threats = []
        for t in grouped.get(c.name, []):
            cell_threats.append({
                "id":          _stable_uuid(t.threat_id),
                "title":       t.title,
                "type":        _STRIDE_LETTER[_cat_value(t)],
                "status":      "Open",
                "severity":    _sev_value(t).capitalize(),
                "description": t.description,
                "mitigation":  t.recommendation,
                "modelType":   "STRIDE",
            })
        cells.append({
            "id":   cell_id,
            "type": _TD_CELL_TYPE.get(c.type.value, "tm.Process"),
            "size": {"width": 160, "height": 80},
            "position": {"x": x, "y": y},
            "data": {
                "type":         "tm.Process",
                "name":         c.name,
                "description":  c.description or "",
                "outOfScope":   False,
                "threats":      cell_threats,
            },
        })
        x += x_step

    return {
        "version":  "2.4",
        "summary":  {
            "title":       f"Threat Model: {system.name}",
            "owner":       "threat-model-generator",
            "description": system.description or "",
        },
        "detail": {
            "contributors": [],
            "diagrams": [{
                "id":          _stable_uuid(f"{system.name}::diagram"),
                "title":       "STRIDE diagram",
                "diagramType": "STRIDE",
                "thumbnail":   "",
                "version":     "2.0",
                "diagramJson": {"cells": cells},
            }],
            "diagramTop": 1,
            "reviewer":   "",
            "threatTop":  len(model.threats),
        },
    }


# ---------------------------------------------------------------------------
# write_outputs
# ---------------------------------------------------------------------------

def write_outputs(
    system: SystemDescription,
    model: ThreatModel,
    *,
    output_path: Path,
    fmt: str = "both",
) -> dict[str, Path]:
    """Write Markdown / Threat Dragon JSON / both. Returns paths written."""
    output_path = Path(output_path).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}

    base = output_path.with_suffix("") if output_path.suffix else output_path

    if fmt in ("markdown", "both"):
        md_path = base.with_suffix(".md")
        md_path.write_text(render_markdown(model), encoding="utf-8")
        written["markdown"] = md_path
    if fmt in ("threatdragon", "both"):
        td_path = base.with_suffix(".json")
        td_path.write_text(
            json.dumps(render_threat_dragon(system, model),
                        indent=2, sort_keys=True),
            encoding="utf-8")
        written["threatdragon"] = td_path
    return written
